# Local MongoDB
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=nyp-email

# Remote MongoDB Atlas
# Username fixed: umu1aksoy instead of umulaksoy
spring.data.mongodb.uri=mongodb+srv://umu1aksoy_db_user:rFSp9dmmCpYdVf9m@e-mail.pgdf9ib.mongodb.net/nyp-email?appName=e-mail

server.port=8080
